### ISSUE TITLE
v3 support?

### ISSUE THREAD

**Issue by charlesomer** [crazy-max/docker-alpine-s6#38]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-alpine-s6/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Looks like this isn't automatically updating with v3 support.

### Expected behaviour

v3 support available.

### Actual behaviour

Stuck at v2.2.0.3-r15

### Steps to reproduce

N/A

### Docker info

```yaml
N/A
```

### Version

N/A

### Docker compose

```yaml
N/A
```

### Container logs

N/A

**Comment by crazy-max** [comment]
Yes working on it

**Comment by charlesomer** [comment]
Ah nice okay, thank you 😄
